using UnityEngine;

public class MyKeyPool : MonoBehaviour
{
    [SerializeField]
    private Sprite _error;
    [SerializeField]
    private MyKeyPoolGamepad _gamepadPs;
    [SerializeField]
    private MyKeyPoolGamepad _gamepadXbox;
    [SerializeField]
    private MyKeyPoolKeyboard _keyboard;
    [SerializeField]
    private MyKeyPoolMouse _mouse;
    [SerializeField]
    private Sprite _null;

    public Sprite GetSprite(string key)
    {
        return key switch
        {
            "<Keyboard>/escape" => GetSprite(MyInput.Keyboard.Escape),
            "<Keyboard>/f1" => GetSprite(MyInput.Keyboard.F1),
            "<Keyboard>/f2" => GetSprite(MyInput.Keyboard.F2),
            "<Keyboard>/f3" => GetSprite(MyInput.Keyboard.F3),
            "<Keyboard>/f4" => GetSprite(MyInput.Keyboard.F4),
            "<Keyboard>/f5" => GetSprite(MyInput.Keyboard.F5),
            "<Keyboard>/f6" => GetSprite(MyInput.Keyboard.F6),
            "<Keyboard>/f7" => GetSprite(MyInput.Keyboard.F7),
            "<Keyboard>/f8" => GetSprite(MyInput.Keyboard.F8),
            "<Keyboard>/f9" => GetSprite(MyInput.Keyboard.F9),
            "<Keyboard>/f10" => GetSprite(MyInput.Keyboard.F10),
            "<Keyboard>/f11" => GetSprite(MyInput.Keyboard.F11),
            "<Keyboard>/f12" => GetSprite(MyInput.Keyboard.F12),
            "<Keyboard>/printScreen" => GetSprite(MyInput.Keyboard.PrintScreen),
            "<Keyboard>/scrollLock" => GetSprite(MyInput.Keyboard.ScrollLock),
            "<Keyboard>/pause" => GetSprite(MyInput.Keyboard.Pause),
            "<Keyboard>/backquote" or
            "<Keyboard>/#(`)" => GetSprite(MyInput.Keyboard.Backtick),
            "<Keyboard>/1" or
            "<Keyboard>/#(1)" => GetSprite(MyInput.Keyboard._1),
            "<Keyboard>/2" or
            "<Keyboard>/#(2)" => GetSprite(MyInput.Keyboard._2),
            "<Keyboard>/3" or
            "<Keyboard>/#(3)" => GetSprite(MyInput.Keyboard._3),
            "<Keyboard>/4" or
            "<Keyboard>/#(4)" => GetSprite(MyInput.Keyboard._4),
            "<Keyboard>/5" or
            "<Keyboard>/#(5)" => GetSprite(MyInput.Keyboard._5),
            "<Keyboard>/6" or
            "<Keyboard>/#(6)" => GetSprite(MyInput.Keyboard._6),
            "<Keyboard>/7" or
            "<Keyboard>/#(7)" => GetSprite(MyInput.Keyboard._7),
            "<Keyboard>/8" or
            "<Keyboard>/#(8)" => GetSprite(MyInput.Keyboard._8),
            "<Keyboard>/9" or
            "<Keyboard>/#(9)" => GetSprite(MyInput.Keyboard._9),
            "<Keyboard>/0" or
            "<Keyboard>/#(0)" => GetSprite(MyInput.Keyboard._0),
            "<Keyboard>/minus" or
            "<Keyboard>/#(-)" => GetSprite(MyInput.Keyboard.Minus),
            "<Keyboard>/equals" or
            "<Keyboard>/#(=)" => GetSprite(MyInput.Keyboard.Equals),
            "<Keyboard>/backslash" or
            "<Keyboard>/#(\\)" => GetSprite(MyInput.Keyboard.Backslash),
            "<Keyboard>/tab" => GetSprite(MyInput.Keyboard.Tab),
            "<Keyboard>/enter" => GetSprite(MyInput.Keyboard.Enter),
            "<Keyboard>/space" => GetSprite(MyInput.Keyboard.Space),
            "<Keyboard>/quote" or
            "<Keyboard>/#(')" => GetSprite(MyInput.Keyboard.SingleQuotation),
            "<Keyboard>/semicolon" or
            "<Keyboard>/#(;)" => GetSprite(MyInput.Keyboard.Semicolon),
            "<Keyboard>/comma" or
            "<Keyboard>/#(,)" => GetSprite(MyInput.Keyboard.Comma),
            "<Keyboard>/period" or
            "<Keyboard>/#(.)" => GetSprite(MyInput.Keyboard.Dot),
            "<Keyboard>/slash" or
            "<Keyboard>/#(/)" => GetSprite(MyInput.Keyboard.Slash),
            "<Keyboard>/leftBracket" or
            "<Keyboard>/#([)" => GetSprite(MyInput.Keyboard.BracketLeft),
            "<Keyboard>/rightBracket" or
            "<Keyboard>/#(])" => GetSprite(MyInput.Keyboard.BracketRight),
            "<Keyboard>/a" or
            "<Keyboard>/#(A)" => GetSprite(MyInput.Keyboard.UpperA),
            "<Keyboard>/b" or
            "<Keyboard>/#(B)" => GetSprite(MyInput.Keyboard.UpperB),
            "<Keyboard>/c" or
            "<Keyboard>/#(C)" => GetSprite(MyInput.Keyboard.UpperC),
            "<Keyboard>/d" or
            "<Keyboard>/#(D)" => GetSprite(MyInput.Keyboard.UpperD),
            "<Keyboard>/e" or
            "<Keyboard>/#(E)" => GetSprite(MyInput.Keyboard.UpperE),
            "<Keyboard>/f" or
            "<Keyboard>/#(F)" => GetSprite(MyInput.Keyboard.UpperF),
            "<Keyboard>/g" or
            "<Keyboard>/#(G)" => GetSprite(MyInput.Keyboard.UpperG),
            "<Keyboard>/h" or
            "<Keyboard>/#(H)" => GetSprite(MyInput.Keyboard.UpperH),
            "<Keyboard>/i" or
            "<Keyboard>/#(I)" => GetSprite(MyInput.Keyboard.UpperI),
            "<Keyboard>/j" or
            "<Keyboard>/#(J)" => GetSprite(MyInput.Keyboard.UpperJ),
            "<Keyboard>/k" or
            "<Keyboard>/#(K)" => GetSprite(MyInput.Keyboard.UpperK),
            "<Keyboard>/l" or
            "<Keyboard>/#(L)" => GetSprite(MyInput.Keyboard.UpperL),
            "<Keyboard>/m" or
            "<Keyboard>/#(M)" => GetSprite(MyInput.Keyboard.UpperM),
            "<Keyboard>/n" or
            "<Keyboard>/#(N)" => GetSprite(MyInput.Keyboard.UpperN),
            "<Keyboard>/o" or
            "<Keyboard>/#(O)" => GetSprite(MyInput.Keyboard.UpperO),
            "<Keyboard>/p" or
            "<Keyboard>/#(P)" => GetSprite(MyInput.Keyboard.UpperP),
            "<Keyboard>/q" or
            "<Keyboard>/#(Q)" => GetSprite(MyInput.Keyboard.UpperQ),
            "<Keyboard>/r" or
            "<Keyboard>/#(R)" => GetSprite(MyInput.Keyboard.UpperR),
            "<Keyboard>/s" or
            "<Keyboard>/#(S)" => GetSprite(MyInput.Keyboard.UpperS),
            "<Keyboard>/t" or
            "<Keyboard>/#(T)" => GetSprite(MyInput.Keyboard.UpperT),
            "<Keyboard>/u" or
            "<Keyboard>/#(U)" => GetSprite(MyInput.Keyboard.UpperU),
            "<Keyboard>/v" or
            "<Keyboard>/#(V)" => GetSprite(MyInput.Keyboard.UpperV),
            "<Keyboard>/w" or
            "<Keyboard>/#(W)" => GetSprite(MyInput.Keyboard.UpperW),
            "<Keyboard>/x" or
            "<Keyboard>/#(X)" => GetSprite(MyInput.Keyboard.UpperX),
            "<Keyboard>/y" or
            "<Keyboard>/#(Y)" => GetSprite(MyInput.Keyboard.UpperY),
            "<Keyboard>/z" or
            "<Keyboard>/#(Z)" => GetSprite(MyInput.Keyboard.UpperZ),
            "<Keyboard>/upArrow" => GetSprite(MyInput.Keyboard.ArrowUp),
            "<Keyboard>/downArrow" => GetSprite(MyInput.Keyboard.ArrowDown),
            "<Keyboard>/leftArrow" => GetSprite(MyInput.Keyboard.ArrowLeft),
            "<Keyboard>/rightArrow" => GetSprite(MyInput.Keyboard.ArrowRight),
            "<Keyboard>/shift" => GetSprite(MyInput.Keyboard.Shift),
            "<Keyboard>/leftShift" => GetSprite(MyInput.Keyboard.ShiftLeft),
            "<Keyboard>/rightShift" => GetSprite(MyInput.Keyboard.ShiftRight),
            "<Keyboard>/alt" => GetSprite(MyInput.Keyboard.Alt),
            "<Keyboard>/leftAlt" => GetSprite(MyInput.Keyboard.AltLeft),
            "<Keyboard>/rightAlt" => GetSprite(MyInput.Keyboard.AltRight),
            "<Keyboard>/ctrl" => GetSprite(MyInput.Keyboard.Ctrl),
            "<Keyboard>/leftCtrl" => GetSprite(MyInput.Keyboard.CtrlLeft),
            "<Keyboard>/rightCtrl" => GetSprite(MyInput.Keyboard.CtrlRight),
            "<Keyboard>/leftMeta" => GetSprite(MyInput.Keyboard.WindowsLeft),
            "<Keyboard>/rightMeta" => GetSprite(MyInput.Keyboard.WindowsRight),
            "<Keyboard>/contextMenu" => GetSprite(MyInput.Keyboard.ContextMenu),
            "<Keyboard>/backspace" => GetSprite(MyInput.Keyboard.Backspace),
            "<Keyboard>/pageDown" => GetSprite(MyInput.Keyboard.PageDown),
            "<Keyboard>/pageUp" => GetSprite(MyInput.Keyboard.PageUp),
            "<Keyboard>/home" => GetSprite(MyInput.Keyboard.Home),
            "<Keyboard>/end" => GetSprite(MyInput.Keyboard.End),
            "<Keyboard>/insert" => GetSprite(MyInput.Keyboard.Insert),
            "<Keyboard>/delete" => GetSprite(MyInput.Keyboard.Delete),
            "<Keyboard>/capsLock" => GetSprite(MyInput.Keyboard.CapsLock),
            "<Keyboard>/numLock" => GetSprite(MyInput.Keyboard.NumLock),
            "<Keyboard>/numpadEnter" => GetSprite(MyInput.Keyboard.NumpadEnter),
            "<Keyboard>/numpadDivide" => GetSprite(MyInput.Keyboard.NumpadSlash),
            "<Keyboard>/numpadMultiply" => GetSprite(MyInput.Keyboard.NumpadAsterisk),
            "<Keyboard>/numpadPlus" => GetSprite(MyInput.Keyboard.NumpadPlus),
            "<Keyboard>/numpadMinus" => GetSprite(MyInput.Keyboard.NumpadMinus),
            "<Keyboard>/numpadPeriod" => GetSprite(MyInput.Keyboard.NumpadDot),
            "<Keyboard>/numpadEquals" => GetSprite(MyInput.Keyboard.Equals),
            "<Keyboard>/numpad1" => GetSprite(MyInput.Keyboard.Numpad1),
            "<Keyboard>/numpad2" => GetSprite(MyInput.Keyboard.Numpad2),
            "<Keyboard>/numpad3" => GetSprite(MyInput.Keyboard.Numpad3),
            "<Keyboard>/numpad4" => GetSprite(MyInput.Keyboard.Numpad4),
            "<Keyboard>/numpad5" => GetSprite(MyInput.Keyboard.Numpad5),
            "<Keyboard>/numpad6" => GetSprite(MyInput.Keyboard.Numpad6),
            "<Keyboard>/numpad7" => GetSprite(MyInput.Keyboard.Numpad7),
            "<Keyboard>/numpad8" => GetSprite(MyInput.Keyboard.Numpad8),
            "<Keyboard>/numpad9" => GetSprite(MyInput.Keyboard.Numpad9),
            "<Keyboard>/numpad0" => GetSprite(MyInput.Keyboard.Numpad0),
            "<Keyboard>/OEM1" => _null,
            "<Keyboard>/OEM2" => _null,
            "<Keyboard>/OEM3" => _null,
            "<Keyboard>/OEM4" => _null,
            "<Keyboard>/OEM5" => _null,
            "<Keyboard>/lang1" => GetSprite(MyInput.Keyboard.Lang1),
            "<Keyboard>/lang2" => GetSprite(MyInput.Keyboard.Lang2),
            "<Keyboard>/muhenkan" => GetSprite(MyInput.Keyboard.Muhenkan),
            "<Keyboard>/henkan" => GetSprite(MyInput.Keyboard.Henkan),
            "<Keyboard>/kana" => GetSprite(MyInput.Keyboard.Kana),
            "<Gamepad>/buttonEast" => GetSprite(MyInput.Controller.Default.ButtonEast),
            "<Gamepad>/buttonNorth" => GetSprite(MyInput.Controller.Default.ButtonNorth),
            "<Gamepad>/buttonSouth" => GetSprite(MyInput.Controller.Default.ButtonSouth),
            "<Gamepad>/buttonWest" => GetSprite(MyInput.Controller.Default.ButtonWest),
            "<opad>/DPad" => GetSprite(MyInput.Controller.Default.DPad),
            "<Gamepad>/dpad/down" => GetSprite(MyInput.Controller.Default.DPadDown),
            "<Gamepad>/dpad/left" => GetSprite(MyInput.Controller.Default.DPadLeft),
            "<Gamepad>/dpad/right" => GetSprite(MyInput.Controller.Default.DPadRight),
            "<Gamepad>/dpad/up" => GetSprite(MyInput.Controller.Default.DPadUp),
            "<Gamepad>/leftShoulder" => GetSprite(MyInput.Controller.Default.LeftBumper),
            "<opad>/LeftStick" => GetSprite(MyInput.Controller.Default.LeftStick),
            "<opad>/LeftStickMove" => GetSprite(MyInput.Controller.Default.LeftStickMove),
            "<Gamepad>/leftStick/down" => GetSprite(MyInput.Controller.Default.LeftStickDown),
            "<Gamepad>/leftStick/left" => GetSprite(MyInput.Controller.Default.LeftStickLeft),
            "<Gamepad>/leftStick/right" => GetSprite(MyInput.Controller.Default.LeftStickRight),
            "<Gamepad>/leftStick/up" => GetSprite(MyInput.Controller.Default.LeftStickUp),
            "<Gamepad>/leftStickPress" => GetSprite(MyInput.Controller.Default.LeftStickPress),
            "<Gamepad>/leftTrigger" => GetSprite(MyInput.Controller.Default.LeftTrigger),
            "<Gamepad>/rightShoulder" => GetSprite(MyInput.Controller.Default.RightBumper),
            "<opad>/RightStick" => GetSprite(MyInput.Controller.Default.RightStick),
            "<opad>/RightStickMove" => GetSprite(MyInput.Controller.Default.RightStickMove),
            "<Gamepad>/rightStick/down" => GetSprite(MyInput.Controller.Default.RightStickDown),
            "<Gamepad>/rightStick/left" => GetSprite(MyInput.Controller.Default.RightStickLeft),
            "<Gamepad>/rightStick/right" => GetSprite(MyInput.Controller.Default.RightStickRight),
            "<Gamepad>/rightStick/up" => GetSprite(MyInput.Controller.Default.RightStickUp),
            "<Gamepad>/rightStickPress" => GetSprite(MyInput.Controller.Default.RightStickPress),
            "<Gamepad>/rightTrigger" => GetSprite(MyInput.Controller.Default.RightTrigger),
            "<Gamepad>/select" => GetSprite(MyInput.Controller.Default.Select),
            "<Gamepad>/start" => GetSprite(MyInput.Controller.Default.Start),
            "<omouse>/Body" => GetSprite(MyInput.Mouse.Body),
            "<Mouse>/leftButton" => GetSprite(MyInput.Mouse.LeftButton),
            "<Mouse>/middleButton" => GetSprite(MyInput.Mouse.MiddleButton),
            "<Mouse>/rightButton" => GetSprite(MyInput.Mouse.RightButton),
            "<omouse>/Direction" => GetSprite(MyInput.Mouse.Direction),
            "<omouse>/DirectionDown" => GetSprite(MyInput.Mouse.DirectionDown),
            "<omouse>/DirectionLeft" => GetSprite(MyInput.Mouse.DirectionLeft),
            "<omouse>/DirectionRight" => GetSprite(MyInput.Mouse.DirectionRight),
            "<omouse>/DirectionUp" => GetSprite(MyInput.Mouse.DirectionUp),
            "<omouse>/WheelDown" => GetSprite(MyInput.Mouse.WheelDown),
            "<omouse>/WheelMove" => GetSprite(MyInput.Mouse.WheelMove),
            "<omouse>/WheelUp" => GetSprite(MyInput.Mouse.WheelUp),
            _ => _error,
        };
    }

    public Sprite GetSprite(MyInput.Controller.Default e)
    {
        return e switch
        {
            MyInput.Controller.Default.ButtonEast => GetSprite(MyInput.Controller.Xbox.ButtonEast),
            MyInput.Controller.Default.ButtonNorth => GetSprite(MyInput.Controller.Xbox.ButtonNorth),
            MyInput.Controller.Default.ButtonSouth => GetSprite(MyInput.Controller.Xbox.ButtonSouth),
            MyInput.Controller.Default.ButtonWest => GetSprite(MyInput.Controller.Xbox.ButtonWest),
            MyInput.Controller.Default.DPad => GetSprite(MyInput.Controller.Xbox.DPad),
            MyInput.Controller.Default.DPadDown => GetSprite(MyInput.Controller.Xbox.DPadDown),
            MyInput.Controller.Default.DPadLeft => GetSprite(MyInput.Controller.Xbox.DPadLeft),
            MyInput.Controller.Default.DPadRight => GetSprite(MyInput.Controller.Xbox.DPadRight),
            MyInput.Controller.Default.DPadUp => GetSprite(MyInput.Controller.Xbox.DPadUp),
            MyInput.Controller.Default.LeftBumper => GetSprite(MyInput.Controller.Xbox.LeftBumper),
            MyInput.Controller.Default.LeftPad => GetSprite(MyInput.Controller.Xbox.LeftPad),
            MyInput.Controller.Default.LeftStick => GetSprite(MyInput.Controller.Xbox.LeftStick),
            MyInput.Controller.Default.LeftStickDown => GetSprite(MyInput.Controller.Xbox.LeftStickDown),
            MyInput.Controller.Default.LeftStickLeft => GetSprite(MyInput.Controller.Xbox.LeftStickLeft),
            MyInput.Controller.Default.LeftStickMove => GetSprite(MyInput.Controller.Xbox.LeftStickMove),
            MyInput.Controller.Default.LeftStickPress => GetSprite(MyInput.Controller.Xbox.LeftStickPress),
            MyInput.Controller.Default.LeftStickRight => GetSprite(MyInput.Controller.Xbox.LeftStickRight),
            MyInput.Controller.Default.LeftStickUp => GetSprite(MyInput.Controller.Xbox.LeftStickUp),
            MyInput.Controller.Default.LeftTrigger => GetSprite(MyInput.Controller.Xbox.LeftTrigger),
            MyInput.Controller.Default.Left3 => GetSprite(MyInput.Controller.Xbox.Left3),
            MyInput.Controller.Default.Left4 => GetSprite(MyInput.Controller.Xbox.Left4),
            MyInput.Controller.Default.Left5 => GetSprite(MyInput.Controller.Xbox.Left5),
            MyInput.Controller.Default.RightBumper => GetSprite(MyInput.Controller.Xbox.RightBumper),
            MyInput.Controller.Default.RightPad => GetSprite(MyInput.Controller.Xbox.RightPad),
            MyInput.Controller.Default.RightStick => GetSprite(MyInput.Controller.Xbox.RightStick),
            MyInput.Controller.Default.RightStickDown => GetSprite(MyInput.Controller.Xbox.RightStickDown),
            MyInput.Controller.Default.RightStickLeft => GetSprite(MyInput.Controller.Xbox.RightStickLeft),
            MyInput.Controller.Default.RightStickMove => GetSprite(MyInput.Controller.Xbox.RightStickMove),
            MyInput.Controller.Default.RightStickPress => GetSprite(MyInput.Controller.Xbox.RightStickPress),
            MyInput.Controller.Default.RightStickRight => GetSprite(MyInput.Controller.Xbox.RightStickRight),
            MyInput.Controller.Default.RightStickUp => GetSprite(MyInput.Controller.Xbox.RightStickUp),
            MyInput.Controller.Default.RightTrigger => GetSprite(MyInput.Controller.Xbox.RightTrigger),
            MyInput.Controller.Default.Right3 => GetSprite(MyInput.Controller.Xbox.Right3),
            MyInput.Controller.Default.Right4 => GetSprite(MyInput.Controller.Xbox.Right4),
            MyInput.Controller.Default.Right5 => GetSprite(MyInput.Controller.Xbox.Right5),
            MyInput.Controller.Default.Select => GetSprite(MyInput.Controller.Xbox.Select),
            MyInput.Controller.Default.Start => GetSprite(MyInput.Controller.Xbox.Start),
            _ => _error,
        };
    }

    public Sprite GetSprite(MyInput.Controller.Playstation e)
    {
        return e switch
        {
            MyInput.Controller.Playstation.ButtonEast => _gamepadPs.ButtonEast,
            MyInput.Controller.Playstation.ButtonNorth => _gamepadPs.ButtonNorth,
            MyInput.Controller.Playstation.ButtonSouth => _gamepadPs.ButtonSouth,
            MyInput.Controller.Playstation.ButtonWest => _gamepadPs.ButtonWest,
            MyInput.Controller.Playstation.DPad => _gamepadPs.DPad,
            MyInput.Controller.Playstation.DPadDown => _gamepadPs.DPadDown,
            MyInput.Controller.Playstation.DPadLeft => _gamepadPs.DPadLeft,
            MyInput.Controller.Playstation.DPadRight => _gamepadPs.DPadRight,
            MyInput.Controller.Playstation.DPadUp => _gamepadPs.DPadUp,
            MyInput.Controller.Playstation.LeftBumper => _gamepadPs.LeftBumper,
            MyInput.Controller.Playstation.LeftPad => _null,
            MyInput.Controller.Playstation.LeftStick => _gamepadPs.LeftStick,
            MyInput.Controller.Playstation.LeftStickMove => _gamepadPs.LeftStickMove,
            MyInput.Controller.Playstation.LeftStickDown => _gamepadPs.LeftStickDown,
            MyInput.Controller.Playstation.LeftStickLeft => _gamepadPs.LeftStickLeft,
            MyInput.Controller.Playstation.LeftStickRight => _gamepadPs.LeftStickRight,
            MyInput.Controller.Playstation.LeftStickUp => _gamepadPs.LeftStickUp,
            MyInput.Controller.Playstation.LeftStickPress => _gamepadPs.LeftStickPress,
            MyInput.Controller.Playstation.LeftTrigger => _gamepadPs.LeftTrigger,
            MyInput.Controller.Playstation.Left3 => _null,
            MyInput.Controller.Playstation.Left4 => _null,
            MyInput.Controller.Playstation.Left5 => _null,
            MyInput.Controller.Playstation.RightBumper => _gamepadPs.RightBumper,
            MyInput.Controller.Playstation.RightPad => _null,
            MyInput.Controller.Playstation.RightStick => _gamepadPs.RightStick,
            MyInput.Controller.Playstation.RightStickMove => _gamepadPs.RightStickMove,
            MyInput.Controller.Playstation.RightStickDown => _gamepadPs.RightStickDown,
            MyInput.Controller.Playstation.RightStickLeft => _gamepadPs.RightStickLeft,
            MyInput.Controller.Playstation.RightStickRight => _gamepadPs.RightStickRight,
            MyInput.Controller.Playstation.RightStickUp => _gamepadPs.RightStickUp,
            MyInput.Controller.Playstation.RightStickPress => _gamepadPs.RightStickPress,
            MyInput.Controller.Playstation.RightTrigger => _gamepadPs.RightTrigger,
            MyInput.Controller.Playstation.Right3 => _null,
            MyInput.Controller.Playstation.Right4 => _null,
            MyInput.Controller.Playstation.Right5 => _null,
            MyInput.Controller.Playstation.Select => _gamepadPs.Select,
            MyInput.Controller.Playstation.Start => _gamepadPs.Start,
            _ => _error,
        };
    }

    public Sprite GetSprite(MyInput.Controller.Xbox e)
    {
        return e switch
        {
            MyInput.Controller.Xbox.ButtonEast => _gamepadXbox.ButtonEast,
            MyInput.Controller.Xbox.ButtonNorth => _gamepadXbox.ButtonNorth,
            MyInput.Controller.Xbox.ButtonSouth => _gamepadXbox.ButtonSouth,
            MyInput.Controller.Xbox.ButtonWest => _gamepadXbox.ButtonWest,
            MyInput.Controller.Xbox.DPad => _gamepadXbox.DPad,
            MyInput.Controller.Xbox.DPadDown => _gamepadXbox.DPadDown,
            MyInput.Controller.Xbox.DPadLeft => _gamepadXbox.DPadLeft,
            MyInput.Controller.Xbox.DPadRight => _gamepadXbox.DPadRight,
            MyInput.Controller.Xbox.DPadUp => _gamepadXbox.DPadUp,
            MyInput.Controller.Xbox.LeftBumper => _gamepadXbox.LeftBumper,
            MyInput.Controller.Xbox.LeftPad => _null,
            MyInput.Controller.Xbox.LeftStick => _gamepadXbox.LeftStick,
            MyInput.Controller.Xbox.LeftStickDown => _gamepadXbox.LeftStickDown,
            MyInput.Controller.Xbox.LeftStickLeft => _gamepadXbox.LeftStickLeft,
            MyInput.Controller.Xbox.LeftStickMove => _gamepadXbox.LeftStickMove,
            MyInput.Controller.Xbox.LeftStickPress => _gamepadXbox.LeftStickPress,
            MyInput.Controller.Xbox.LeftStickRight => _gamepadXbox.LeftStickRight,
            MyInput.Controller.Xbox.LeftStickUp => _gamepadXbox.LeftStickUp,
            MyInput.Controller.Xbox.LeftTrigger => _gamepadXbox.LeftTrigger,
            MyInput.Controller.Xbox.Left3 => _null,
            MyInput.Controller.Xbox.Left4 => _null,
            MyInput.Controller.Xbox.Left5 => _null,
            MyInput.Controller.Xbox.RightBumper => _gamepadXbox.RightBumper,
            MyInput.Controller.Xbox.RightPad => _null,
            MyInput.Controller.Xbox.RightStick => _gamepadXbox.RightStick,
            MyInput.Controller.Xbox.RightStickDown => _gamepadXbox.RightStickDown,
            MyInput.Controller.Xbox.RightStickLeft => _gamepadXbox.RightStickLeft,
            MyInput.Controller.Xbox.RightStickMove => _gamepadXbox.RightStickMove,
            MyInput.Controller.Xbox.RightStickPress => _gamepadXbox.RightStickPress,
            MyInput.Controller.Xbox.RightStickRight => _gamepadXbox.RightStickRight,
            MyInput.Controller.Xbox.RightStickUp => _gamepadXbox.RightStickUp,
            MyInput.Controller.Xbox.RightTrigger => _gamepadXbox.RightTrigger,
            MyInput.Controller.Xbox.Right3 => _null,
            MyInput.Controller.Xbox.Right4 => _null,
            MyInput.Controller.Xbox.Right5 => _null,
            MyInput.Controller.Xbox.Select => _gamepadXbox.Select,
            MyInput.Controller.Xbox.Start => _gamepadXbox.Start,
            _ => _error,
        };
    }

    public Sprite GetSprite(MyInput.Keyboard e)
    {
        return e switch
        {
            MyInput.Keyboard._0 => _keyboard._0,
            MyInput.Keyboard._1 => _keyboard._1,
            MyInput.Keyboard._2 => _keyboard._2,
            MyInput.Keyboard._3 => _keyboard._3,
            MyInput.Keyboard._4 => _keyboard._4,
            MyInput.Keyboard._5 => _keyboard._5,
            MyInput.Keyboard._6 => _keyboard._6,
            MyInput.Keyboard._7 => _keyboard._7,
            MyInput.Keyboard._8 => _keyboard._8,
            MyInput.Keyboard._9 => _keyboard._9,
            MyInput.Keyboard.Alt => _keyboard.Alt,
            MyInput.Keyboard.AltLeft => _keyboard.AltLeft,
            MyInput.Keyboard.AltRight => _keyboard.AltRight,
            MyInput.Keyboard.Ampersand => _keyboard.Ampersand,
            MyInput.Keyboard.AngleBracketLeft => _keyboard.AngleBracketLeft,
            MyInput.Keyboard.AngleBracketRight => _keyboard.AngleBracketRight,
            MyInput.Keyboard.ArrowDown => _keyboard.ArrowDown,
            MyInput.Keyboard.ArrowLeft => _keyboard.ArrowLeft,
            MyInput.Keyboard.ArrowRight => _keyboard.ArrowRight,
            MyInput.Keyboard.ArrowUp => _keyboard.ArrowUp,
            MyInput.Keyboard.Asterisk => _keyboard.Asterisk,
            MyInput.Keyboard.At => _keyboard.At,
            MyInput.Keyboard.Backslash => _keyboard.Backslash,
            MyInput.Keyboard.Backspace => _keyboard.Backspace,
            MyInput.Keyboard.Backtick => _keyboard.Backtick,
            MyInput.Keyboard.BracketLeft => _keyboard.BracketLeft,
            MyInput.Keyboard.BracketRight => _keyboard.BracketRight,
            MyInput.Keyboard.CapsLock => _keyboard.CapsLock,
            MyInput.Keyboard.Caret => _keyboard.Caret,
            MyInput.Keyboard.Colon => _keyboard.Colon,
            MyInput.Keyboard.Comma => _keyboard.Comma,
            MyInput.Keyboard.ContextMenu => _keyboard.ContextMenu,
            MyInput.Keyboard.Ctrl => _keyboard.Ctrl,
            MyInput.Keyboard.CtrlLeft => _keyboard.CtrlLeft,
            MyInput.Keyboard.CtrlRight => _keyboard.CtrlRight,
            MyInput.Keyboard.CurlyBracketLeft => _keyboard.CurlyBracketLeft,
            MyInput.Keyboard.CurlyBracketRight => _keyboard.CurlyBracketRight,
            MyInput.Keyboard.Delete => _keyboard.Delete,
            MyInput.Keyboard.DollarSign => _keyboard.DollarSign,
            MyInput.Keyboard.Dot => _keyboard.Dot,
            MyInput.Keyboard.DoubleQuotation => _keyboard.DoubleQuotation,
            MyInput.Keyboard.End => _keyboard.End,
            MyInput.Keyboard.Enter => _keyboard.Enter,
            MyInput.Keyboard.Equals => _keyboard._Equals,
            MyInput.Keyboard.Escape => _keyboard.Escape,
            MyInput.Keyboard.ExclamationMark => _keyboard.ExclamationMark,
            MyInput.Keyboard.F1 => _keyboard.F1,
            MyInput.Keyboard.F2 => _keyboard.F2,
            MyInput.Keyboard.F3 => _keyboard.F3,
            MyInput.Keyboard.F4 => _keyboard.F4,
            MyInput.Keyboard.F5 => _keyboard.F5,
            MyInput.Keyboard.F6 => _keyboard.F6,
            MyInput.Keyboard.F7 => _keyboard.F7,
            MyInput.Keyboard.F8 => _keyboard.F8,
            MyInput.Keyboard.F9 => _keyboard.F9,
            MyInput.Keyboard.F10 => _keyboard.F10,
            MyInput.Keyboard.F11 => _keyboard.F11,
            MyInput.Keyboard.F12 => _keyboard.F12,
            MyInput.Keyboard.Henkan => _keyboard.Henkan,
            MyInput.Keyboard.Home => _keyboard.Home,
            MyInput.Keyboard.Insert => _keyboard.Insert,
            MyInput.Keyboard.Kana => _keyboard.Kana,
            MyInput.Keyboard.Lang1 => _keyboard.Lang1,
            MyInput.Keyboard.Lang2 => _keyboard.Lang2,
            MyInput.Keyboard.LowerA => _keyboard.LowerA,
            MyInput.Keyboard.LowerB => _keyboard.LowerB,
            MyInput.Keyboard.LowerC => _keyboard.LowerC,
            MyInput.Keyboard.LowerD => _keyboard.LowerD,
            MyInput.Keyboard.LowerE => _keyboard.LowerE,
            MyInput.Keyboard.LowerF => _keyboard.LowerF,
            MyInput.Keyboard.LowerG => _keyboard.LowerG,
            MyInput.Keyboard.LowerH => _keyboard.LowerH,
            MyInput.Keyboard.LowerI => _keyboard.LowerI,
            MyInput.Keyboard.LowerJ => _keyboard.LowerJ,
            MyInput.Keyboard.LowerK => _keyboard.LowerK,
            MyInput.Keyboard.LowerL => _keyboard.LowerL,
            MyInput.Keyboard.LowerM => _keyboard.LowerM,
            MyInput.Keyboard.LowerN => _keyboard.LowerN,
            MyInput.Keyboard.LowerO => _keyboard.LowerO,
            MyInput.Keyboard.LowerP => _keyboard.LowerP,
            MyInput.Keyboard.LowerQ => _keyboard.LowerQ,
            MyInput.Keyboard.LowerR => _keyboard.LowerR,
            MyInput.Keyboard.LowerS => _keyboard.LowerS,
            MyInput.Keyboard.LowerT => _keyboard.LowerT,
            MyInput.Keyboard.LowerU => _keyboard.LowerU,
            MyInput.Keyboard.LowerV => _keyboard.LowerV,
            MyInput.Keyboard.LowerW => _keyboard.LowerW,
            MyInput.Keyboard.LowerX => _keyboard.LowerX,
            MyInput.Keyboard.LowerY => _keyboard.LowerY,
            MyInput.Keyboard.LowerZ => _keyboard.LowerZ,
            MyInput.Keyboard.LowLine => _keyboard.LowLine,
            MyInput.Keyboard.Minus => _keyboard.Minus,
            MyInput.Keyboard.Muhenkan => _keyboard.Muhenkan,
            MyInput.Keyboard.NumberSign => _keyboard.NumberSign,
            MyInput.Keyboard.NumLock => _keyboard.NumLock,
            MyInput.Keyboard.Numpad0 => _keyboard.Numpad0,
            MyInput.Keyboard.Numpad1 => _keyboard.Numpad1,
            MyInput.Keyboard.Numpad2 => _keyboard.Numpad2,
            MyInput.Keyboard.Numpad3 => _keyboard.Numpad3,
            MyInput.Keyboard.Numpad4 => _keyboard.Numpad4,
            MyInput.Keyboard.Numpad5 => _keyboard.Numpad5,
            MyInput.Keyboard.Numpad6 => _keyboard.Numpad6,
            MyInput.Keyboard.Numpad7 => _keyboard.Numpad7,
            MyInput.Keyboard.Numpad8 => _keyboard.Numpad8,
            MyInput.Keyboard.Numpad9 => _keyboard.Numpad9,
            MyInput.Keyboard.NumpadAsterisk => _keyboard.NumpadAsterisk,
            MyInput.Keyboard.NumpadDot => _keyboard.NumpadDot,
            MyInput.Keyboard.NumpadEnter => _keyboard.NumpadEnter,
            MyInput.Keyboard.NumpadMinus => _keyboard.NumpadMinus,
            MyInput.Keyboard.NumpadPlus => _keyboard.NumpadPlus,
            MyInput.Keyboard.NumpadSlash => _keyboard.NumpadSlash,
            MyInput.Keyboard.PageDown => _keyboard.PageDown,
            MyInput.Keyboard.PageUp => _keyboard.PageUp,
            MyInput.Keyboard.ParenthesisLeft => _keyboard.ParenthesisLeft,
            MyInput.Keyboard.ParenthesisRight => _keyboard.ParenthesisRight,
            MyInput.Keyboard.Pause => _keyboard.Pause,
            MyInput.Keyboard.PercentSign => _keyboard.PercentSign,
            MyInput.Keyboard.Plus => _keyboard.Plus,
            MyInput.Keyboard.PrintScreen => _keyboard.PrintScreen,
            MyInput.Keyboard.QuestionMark => _keyboard.QuestionMark,
            MyInput.Keyboard.ScrollLock => _keyboard.ScrollLock,
            MyInput.Keyboard.Semicolon => _keyboard.Semicolon,
            MyInput.Keyboard.Shift => _keyboard.Shift,
            MyInput.Keyboard.ShiftLeft => _keyboard.ShiftLeft,
            MyInput.Keyboard.ShiftRight => _keyboard.ShiftRight,
            MyInput.Keyboard.SingleQuotation => _keyboard.SingleQuotation,
            MyInput.Keyboard.Slash => _keyboard.Slash,
            MyInput.Keyboard.Space => _keyboard.Space,
            MyInput.Keyboard.Tab => _keyboard.Tab,
            MyInput.Keyboard.Tilde => _keyboard.Tilde,
            MyInput.Keyboard.UpperA => _keyboard.UpperA,
            MyInput.Keyboard.UpperB => _keyboard.UpperB,
            MyInput.Keyboard.UpperC => _keyboard.UpperC,
            MyInput.Keyboard.UpperD => _keyboard.UpperD,
            MyInput.Keyboard.UpperE => _keyboard.UpperE,
            MyInput.Keyboard.UpperF => _keyboard.UpperF,
            MyInput.Keyboard.UpperG => _keyboard.UpperG,
            MyInput.Keyboard.UpperH => _keyboard.UpperH,
            MyInput.Keyboard.UpperI => _keyboard.UpperI,
            MyInput.Keyboard.UpperJ => _keyboard.UpperJ,
            MyInput.Keyboard.UpperK => _keyboard.UpperK,
            MyInput.Keyboard.UpperL => _keyboard.UpperL,
            MyInput.Keyboard.UpperM => _keyboard.UpperM,
            MyInput.Keyboard.UpperN => _keyboard.UpperN,
            MyInput.Keyboard.UpperO => _keyboard.UpperO,
            MyInput.Keyboard.UpperP => _keyboard.UpperP,
            MyInput.Keyboard.UpperQ => _keyboard.UpperQ,
            MyInput.Keyboard.UpperR => _keyboard.UpperR,
            MyInput.Keyboard.UpperS => _keyboard.UpperS,
            MyInput.Keyboard.UpperT => _keyboard.UpperT,
            MyInput.Keyboard.UpperU => _keyboard.UpperU,
            MyInput.Keyboard.UpperV => _keyboard.UpperV,
            MyInput.Keyboard.UpperW => _keyboard.UpperW,
            MyInput.Keyboard.UpperX => _keyboard.UpperX,
            MyInput.Keyboard.UpperY => _keyboard.UpperY,
            MyInput.Keyboard.UpperZ => _keyboard.UpperZ,
            MyInput.Keyboard.VerticalBar => _keyboard.VerticalBar,
            MyInput.Keyboard.Windows => _keyboard.Windows,
            MyInput.Keyboard.WindowsLeft => _keyboard.WindowsLeft,
            MyInput.Keyboard.WindowsRight => _keyboard.WindowsRight,
            _ => _error,
        };
    }

    public Sprite GetSprite(MyInput.Mouse e)
    {
        return e switch
        {
            MyInput.Mouse.Body => _mouse.Body,
            MyInput.Mouse.Direction => _mouse.Direction,
            MyInput.Mouse.DirectionDown => _mouse.DirectionDown,
            MyInput.Mouse.DirectionLeft => _mouse.DirectionLeft,
            MyInput.Mouse.DirectionRight => _mouse.DirectionRight,
            MyInput.Mouse.DirectionUp => _mouse.DirectionUp,
            MyInput.Mouse.LeftButton => _mouse.LeftButton,
            MyInput.Mouse.MiddleButton => _mouse.MiddleButton,
            MyInput.Mouse.RightButton => _mouse.RightButton,
            MyInput.Mouse.WheelDown => _mouse.WheelDown,
            MyInput.Mouse.WheelMove => _mouse.WheelMove,
            MyInput.Mouse.WheelUp => _mouse.WheelUp,
            _ => _error,
        };
    }
}
